POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwiZXhwIjoxNzE2MDE3NDM1LCJ1c2VySUQiOjJ9.LXwEAy8Pwvcmj-w-QnX5YLLjZOdEpguawL75GG85eO0

{
  "name": "Event 1",
  "description": "Event 1 description",
  "datetime": "2021-12-31T23:59:59.000Z",
  "location": "Event 1 location"
}